[package]
name = "messenger"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["multipart", "macros", "ws"] }
tower = { version = "0.5", features = ["util"] }
dotenv = "0.15.0"
tower-http = { version = "0.6.2", features = ["cors", "fs"] }
serde = "1.0.197"
serde_derive = "1.0.197"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "runtime-tokio-rustls", "chrono", "uuid", "json"] }
tokio = { version = "1.4.0", features = ["rt", "rt-multi-thread", "macros"] }
tracing-subscriber = "0.3.18"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
chrono = { version = "0.4.*", features = ["serde"] }
rand = "0.9.0"
argon2 = "0.5"
rand_core = "0.9.2"
jsonwebtoken = "9.3.1"
utoipa = { version = "5.4", features = ["uuid", "chrono", "axum_extras"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
utoipa-axum = { version = "0.2" }
mime_guess = "2.0.5"
futures = "0.3.31"
num-format = "0.4.4"
regex = "1.12.2"
lettre = { version = "0.11", default-features = false, features = [
    "smtp-transport",
    "builder",
    "tokio1-rustls",
    "ring",
    "webpki-roots",
] }
tracing = "0.1.44"
serde_json = "1.0.149"
http = "1.4.0"
async-trait = "0.1.89"

[profile.release]
strip = true
lto = true
panic = 'abort'
